### ISSUE TITLE
关于SnakeLANd的修改许可申请~

### ISSUE THREAD

**Issue by mickey0451** [tonyzhang617/multiplayer-snake#6]
Hi tony:
    你好，我是华为公司的王明琦。无意中发现了你的这个游戏作品SnakeLANd，感觉非常棒！
    最近华为公司向开发者发布了HMS（HUAWEI Mobile Service），其中的Nearby Service（近距离通信服务）可以实现附近设备之间的发现，连接，传输数据。
    Nearby Service对比Kryonet的优势在于，不必在同一个WIFI下才能互联。在户外，甚至在飞机上都可以一起玩SnakeLANd。
    所以，我想基于你的作品的基础上做一些修改，把kryonet替换为HMS Nearby Service。另外我还想加入中文版和游戏速度选择等一些改动。
    改好后，我想把你的作品作为示例代码放在华为的开发者论坛上，当然作者会以你的名义，并保留原有的License声明。
   期待你的答复，祝顺利！

**Comment by tonyzhang617** [comment]
王明琦你好，

没有问题。很久都没有update这个project了，所以有一些bug。有任何问题可以问我。

Tony
